// Generates `main.go` for the Go runner from a question's signature + user code.
// Mirrors generate-rust.mjs in scope: function (return / mutation) + design.
// Codec round-trip is deferred (1 problem marked backendUnsupported).
//
// Wire protocol (stdin → stdout):
//   in:  {"tests":[{"input":{...}, "output":<expected>}, ...]}
//   out: {"results":[{"index":0, "ok":true, "actual":<json>, "durationMs":5}, ...]}
// Pass/fail comparison happens in JS-land using question.comparison.

const PRELUDE = `// Auto-generated by AlgoTutor. Do not edit by hand.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"time"
)

var _ = fmt.Sprintf
var _ = time.Now

// === Standard data structures (canonical) ===
type ListNode struct {
	Val  int
	Next *ListNode
}

type TreeNode struct {
	Val   int
	Left  *TreeNode
	Right *TreeNode
}

// === Wire adapters ===
func arrayToList(arr []int) *ListNode {
	var head *ListNode
	for i := len(arr) - 1; i >= 0; i-- {
		head = &ListNode{Val: arr[i], Next: head}
	}
	return head
}

func listToArray(head *ListNode) []int {
	out := []int{}
	for head != nil {
		out = append(out, head.Val)
		head = head.Next
	}
	return out
}

func arrayToTree(arr []*int) *TreeNode {
	if len(arr) == 0 || arr[0] == nil {
		return nil
	}
	root := &TreeNode{Val: *arr[0]}
	q := []*TreeNode{root}
	i := 1
	for len(q) > 0 && i < len(arr) {
		node := q[0]
		q = q[1:]
		if i < len(arr) {
			if arr[i] != nil {
				node.Left = &TreeNode{Val: *arr[i]}
				q = append(q, node.Left)
			}
			i++
		}
		if i < len(arr) {
			if arr[i] != nil {
				node.Right = &TreeNode{Val: *arr[i]}
				q = append(q, node.Right)
			}
			i++
		}
	}
	return root
}

func treeToArray(root *TreeNode) []*int {
	out := []*int{}
	if root == nil {
		return out
	}
	type qe struct{ n *TreeNode }
	q := []qe{{root}}
	for len(q) > 0 {
		front := q[0]
		q = q[1:]
		if front.n == nil {
			out = append(out, nil)
			continue
		}
		v := front.n.Val
		out = append(out, &v)
		q = append(q, qe{front.n.Left}, qe{front.n.Right})
	}
	for len(out) > 0 && out[len(out)-1] == nil {
		out = out[:len(out)-1]
	}
	return out
}

// === Wire-shape structs for graph/random-list problems ===
type RandomList struct {
	Vals    []int  \`json:"vals"\`
	Randoms []*int \`json:"randoms"\`
}
type GraphRepr struct {
	Nodes []int   \`json:"nodes"\`
	Adj   [][]int \`json:"adj"\`
}

`;

// Map a paramAdapter to the wire-side Go type.
function wireType(paramAdapter) {
  switch (paramAdapter) {
    case "arrayToLinkedList": return "[]int";
    case "arrayToBinaryTree": return "[]*int";
    default: return null; // identity → use the user type
  }
}

// Build a Go struct field declaration with a json tag.
function structField(name, type_) {
  // Capitalize for export.
  const exported = name.charAt(0).toUpperCase() + name.slice(1);
  return `\t${exported} ${type_} \`json:"${name}"\``;
}

// Generate the binding from input.<Name> → user-callable value.
function bindParam(p, i, isMutationIdx) {
  const exported = p.name.charAt(0).toUpperCase() + p.name.slice(1);
  const inputExpr = `input.${exported}`;
  let bindExpr;
  switch (p.adapt) {
    case "arrayToLinkedList":
      bindExpr = `arrayToList(${inputExpr})`;
      break;
    case "arrayToBinaryTree":
      bindExpr = `arrayToTree(${inputExpr})`;
      break;
    default:
      bindExpr = inputExpr;
  }
  return `\t\t${p.name} := ${bindExpr}`;
}

// Generate the call expression: e.g., `twoSum(nums, target)` or `nums = twoSum(nums, target)`.
function callExpr(fnName, params) {
  const args = params.map((p) => p.name).join(", ");
  return `${fnName}(${args})`;
}

// Generate an expression that converts the user's return value into a JSON-marshalable value.
function actualExpr(returnAdapt, returnType) {
  switch (returnAdapt) {
    case "linkedListToArray":     return "listToArray(__ret)";
    case "binaryTreeToLevelOrder": return "treeToArray(__ret)";
    default: return "__ret";
  }
}

export function generateGoFunctionHarness(question, userCode) {
  const sig = question.signature;
  const fnName = sig.fn;
  const ct = sig.codeTypes.go;
  const judge = sig.judgeSource || "return";
  const isMutation = judge.startsWith("param:");
  const mutIdx = isMutation ? Number(judge.slice(6)) : -1;
  const isPrefixReturn = judge === "param0PrefixWithReturn";

  const params = sig.params.map((p, i) => {
    const ut = ct.params[i].type;
    const wt = wireType(p.adapt) || ut;
    return { name: p.name, userType: ut, wireType: wt, adapt: p.adapt || "identity" };
  });

  const fields = params.map((p) => structField(p.name, p.wireType)).join("\n");

  const bindLines = params.map((p, i) => bindParam(p, i, mutIdx)).join("\n");

  // Build the call + actual extraction, both in the catch-panic block.
  let callBlock;
  if (isMutation) {
    const mutParam = params[mutIdx];
    let mutSerialize;
    switch (mutParam.adapt) {
      case "arrayToLinkedList":
        mutSerialize = `listToArray(${mutParam.name})`;
        break;
      case "arrayToBinaryTree":
        mutSerialize = `treeToArray(${mutParam.name})`;
        break;
      default:
        mutSerialize = mutParam.name;
    }
    callBlock = `\t\t\t${callExpr(fnName, params)}
\t\t\tactualVal = ${mutSerialize}`;
  } else if (isPrefixReturn) {
    const p0 = params[0];
    callBlock = `\t\t\t__ret := ${callExpr(fnName, params)}
\t\t\t__k := __ret
\t\t\tif __k < 0 { __k = 0 }
\t\t\tif __k > len(${p0.name}) { __k = len(${p0.name}) }
\t\t\t__prefix := append([]int{}, ${p0.name}[:__k]...)
\t\t\tactualVal = []interface{}{__ret, __prefix}`;
  } else {
    callBlock = `\t\t\t__ret := ${callExpr(fnName, params)}
\t\t\tactualVal = ${actualExpr(sig.returnAdapt || "identity", ct.returns)}`;
  }

  return `${PRELUDE}
// === User code ===
${userCode}
// === End user code ===

type TestInput struct {
${fields}
}

type Test struct {
	Input  TestInput       \`json:"input"\`
	Output json.RawMessage \`json:"output"\`
}

type Request struct {
	Tests []Test \`json:"tests"\`
}

type CaseResult struct {
	Index      int             \`json:"index"\`
	OK         bool            \`json:"ok"\`
	Actual     json.RawMessage \`json:"actual,omitempty"\`
	DurationMs int64           \`json:"durationMs"\`
	Error      string          \`json:"error,omitempty"\`
}

type Response struct {
	Results []CaseResult \`json:"results"\`
}

func runOneCase(i int, t Test) (cr CaseResult) {
	cr.Index = i
	started := time.Now()
	defer func() {
		cr.DurationMs = time.Since(started).Milliseconds()
		if r := recover(); r != nil {
			cr.OK = false
			cr.Error = fmt.Sprintf("%v", r)
		}
	}()
	input := t.Input
	_ = input
	var actualVal interface{}
	func() {
${bindLines}
${callBlock}
	}()
	bs, err := json.Marshal(actualVal)
	if err != nil {
		cr.OK = false
		cr.Error = "marshal: " + err.Error()
		return
	}
	cr.OK = true
	cr.Actual = bs
	return
}

func main() {
	buf, err := io.ReadAll(os.Stdin)
	if err != nil {
		fmt.Fprintf(os.Stderr, "__HARNESS_READ_ERROR__: %v\\n", err)
		os.Exit(2)
	}
	var req Request
	if err := json.Unmarshal(buf, &req); err != nil {
		fmt.Fprintf(os.Stderr, "__HARNESS_PARSE_ERROR__: %v\\n", err)
		os.Exit(2)
	}
	out := make([]CaseResult, 0, len(req.Tests))
	for i, t := range req.Tests {
		out = append(out, runOneCase(i, t))
	}
	resp := Response{Results: out}
	bs, _ := json.Marshal(resp)
	os.Stdout.Write(bs)
}
`;
}

// === Design harness ===
export function generateGoDesignHarness(question, userCode) {
  const sig = question.signature;
  const design = sig.design;
  const className = design.className;
  const ctorParams = (design.ctor && design.ctor.params) || [];
  const methods = design.methods || [];

  // The user-defined struct in Go convention has methods with pointer receivers.
  // The constructor is conventionally a top-level `Constructor(args...) {ClassName}`.
  // ( Go template.) We'll call it as `{className}_New` if you adopted a
  // different convention — but standard is `Constructor`. We assume `Constructor`.

  const ctorArgBindings = ctorParams.map((p, i) => {
    const t = p.type.go;
    return `\t\t\tvar __c${i} ${t}
\t\t\tif err := json.Unmarshal(args[${i}], &__c${i}); err != nil { panic(fmt.Sprintf("ctor arg ${i} (${p.name}) parse: %v", err)) }`;
  }).join("\n");
  const ctorArgList = ctorParams.map((_, i) => `__c${i}`).join(", ");

  const methodArms = methods.map((m) => {
    const argBindings = m.params.map((p, i) => {
      const t = p.type.go;
      return `\t\t\t\tvar __a${i} ${t}
\t\t\t\tif err := json.Unmarshal(args[${i}], &__a${i}); err != nil { panic(fmt.Sprintf("${m.name} arg ${i} (${p.name}) parse: %v", err)) }`;
    }).join("\n");
    const argList = m.params.map((_, i) => `__a${i}`).join(", ");
    const ret = (m.returns && m.returns.go) || "";
    const isVoid = ret === "" || ret == null;
    let callBlock;
    if (isVoid) {
      callBlock = `\t\t\t\tinst.${m.name}(${argList})
\t\t\t\tout = append(out, json.RawMessage("null"))`;
    } else {
      callBlock = `\t\t\t\t__r := inst.${m.name}(${argList})
\t\t\t\tbs, _ := json.Marshal(__r)
\t\t\t\tout = append(out, json.RawMessage(bs))`;
    }
    return `\t\tcase "${m.name}":
${argBindings}
${callBlock}`;
  }).join("\n");

  const fallbackCtor = ctorParams.length === 0
    ? `inst = newInst()`
    : `panic("first op should be the constructor (${className}) for this problem")`;

  const newInstHelper = ctorParams.length === 0
    ? `// Helper for "ctor not in stream" fallback (zero-param ctor only).
func newInst() *${className} {
	v := Constructor()
	return &v
}`
    : "";

  return `${PRELUDE}
// === User code ===
${userCode}
// === End user code ===

type DesignInput struct {
	Ops        [][]json.RawMessage \`json:"ops,omitempty"\`
	Operations []string            \`json:"operations,omitempty"\`
	Args       [][]json.RawMessage \`json:"args,omitempty"\`
}

type Test struct {
	Input  DesignInput     \`json:"input"\`
	Output json.RawMessage \`json:"output"\`
}

type Request struct {
	Tests []Test \`json:"tests"\`
}

type CaseResult struct {
	Index      int             \`json:"index"\`
	OK         bool            \`json:"ok"\`
	Actual     json.RawMessage \`json:"actual,omitempty"\`
	DurationMs int64           \`json:"durationMs"\`
	Error      string          \`json:"error,omitempty"\`
}

type Response struct {
	Results []CaseResult \`json:"results"\`
}

// Helper to construct a default-initialized instance for "ctor not in stream"
// (only used when ctor has zero params).
${newInstHelper}

func runOneCase(i int, t Test) (cr CaseResult) {
	cr.Index = i
	started := time.Now()
	defer func() {
		cr.DurationMs = time.Since(started).Milliseconds()
		if r := recover(); r != nil {
			cr.OK = false
			cr.Error = fmt.Sprintf("%v", r)
		}
	}()
	input := t.Input
	var methods []string
	var allArgs [][]json.RawMessage
	if len(input.Ops) > 0 {
		methods = make([]string, 0, len(input.Ops))
		allArgs = make([][]json.RawMessage, 0, len(input.Ops))
		for _, op := range input.Ops {
			if len(op) == 0 {
				panic("empty op tuple")
			}
			var name string
			if err := json.Unmarshal(op[0], &name); err != nil {
				panic(fmt.Sprintf("op[0] not a string: %v", err))
			}
			methods = append(methods, name)
			allArgs = append(allArgs, op[1:])
		}
	} else {
		methods = input.Operations
		allArgs = input.Args
	}

	out := make([]json.RawMessage, 0, len(methods))
	var inst *${className}
	for idx, name := range methods {
		var args []json.RawMessage
		if idx < len(allArgs) {
			args = allArgs[idx]
		}
		if name == "${className}" {
${ctorArgBindings}
			v := Constructor(${ctorArgList})
			inst = &v
			out = append(out, json.RawMessage("null"))
			continue
		}
		if inst == nil {
			${fallbackCtor}
		}
		switch name {
${methodArms}
		default:
			panic("unknown method: " + name)
		}
	}
	bs, err := json.Marshal(out)
	if err != nil {
		cr.OK = false
		cr.Error = "marshal: " + err.Error()
		return
	}
	cr.OK = true
	cr.Actual = bs
	return
}

func main() {
	buf, err := io.ReadAll(os.Stdin)
	if err != nil {
		fmt.Fprintf(os.Stderr, "__HARNESS_READ_ERROR__: %v\\n", err)
		os.Exit(2)
	}
	var req Request
	if err := json.Unmarshal(buf, &req); err != nil {
		fmt.Fprintf(os.Stderr, "__HARNESS_PARSE_ERROR__: %v\\n", err)
		os.Exit(2)
	}
	out := make([]CaseResult, 0, len(req.Tests))
	for i, t := range req.Tests {
		out = append(out, runOneCase(i, t))
	}
	resp := Response{Results: out}
	bs, _ := json.Marshal(resp)
	os.Stdout.Write(bs)
}
`;
}

// === Codec round-trip harness ===
// User defines `type Codec struct{}`, `func Constructor() Codec`, and pointer-receiver methods
// `serialize(root *TreeNode) string` and `deserialize(data string) *TreeNode`.
// Wire input: { tree: []*int }. We materialize the tree, drive the round-trip,
// and emit the resulting tree as `actual` in level-order form.
export function generateGoCodecHarness(question, userCode) {
  return `${PRELUDE}
// === User code ===
${userCode}
// === End user code ===

type TestInput struct {
	Tree []*int \`json:"tree"\`
}

type Test struct {
	Input  TestInput       \`json:"input"\`
	Output json.RawMessage \`json:"output"\`
}

type Request struct {
	Tests []Test \`json:"tests"\`
}

type CaseResult struct {
	Index      int             \`json:"index"\`
	OK         bool            \`json:"ok"\`
	Actual     json.RawMessage \`json:"actual,omitempty"\`
	DurationMs int64           \`json:"durationMs"\`
	Error      string          \`json:"error,omitempty"\`
}

type Response struct {
	Results []CaseResult \`json:"results"\`
}

func runOneCase(i int, t Test) (cr CaseResult) {
	cr.Index = i
	started := time.Now()
	defer func() {
		cr.DurationMs = time.Since(started).Milliseconds()
		if r := recover(); r != nil {
			cr.OK = false
			cr.Error = fmt.Sprintf("%v", r)
		}
	}()
	root := arrayToTree(t.Input.Tree)
	c := Constructor()
	codec := &c
	s := codec.serialize(root)
	r := codec.deserialize(s)
	arr := treeToArray(r)
	bs, err := json.Marshal(arr)
	if err != nil {
		cr.OK = false
		cr.Error = "marshal: " + err.Error()
		return
	}
	cr.OK = true
	cr.Actual = bs
	return
}

func main() {
	buf, err := io.ReadAll(os.Stdin)
	if err != nil {
		fmt.Fprintf(os.Stderr, "__HARNESS_READ_ERROR__: %v\\n", err)
		os.Exit(2)
	}
	var req Request
	if err := json.Unmarshal(buf, &req); err != nil {
		fmt.Fprintf(os.Stderr, "__HARNESS_PARSE_ERROR__: %v\\n", err)
		os.Exit(2)
	}
	out := make([]CaseResult, 0, len(req.Tests))
	for i, t := range req.Tests {
		out = append(out, runOneCase(i, t))
	}
	resp := Response{Results: out}
	bs, _ := json.Marshal(resp)
	os.Stdout.Write(bs)
}
`;
}

export function generateGoHarness(question, userCode) {
  const kind = question.signature.kind || "function";
  if (kind === "function") return generateGoFunctionHarness(question, userCode);
  if (kind === "design") return generateGoDesignHarness(question, userCode);
  if (kind === "codec-roundtrip") return generateGoCodecHarness(question, userCode);
  throw new Error(`unsupported kind for Go: ${kind}`);
}
