// Generates `main.rs` for the Rust runner crate from a question's signature
// and user code. Phase D.1 scope:
//   - kind: "function"
//   - judgeSource: "return" or "param:N"
//   - param adapters: identity, arrayToLinkedList, arrayToBinaryTree
//   - return adapters: identity, linkedListToArray, binaryTreeToLevelOrder
// Wire protocol (stdin → stdout):
//   in:  {"tests":[{"input":{...}, "output":<expected>}, ...]}
//   out: {"results":[{"index":0, "ok":true, "actual":<json>, "durationMs":5}, ...]}
// Pass/fail comparison happens in JS-land using question.comparison.

const PRELUDE = `// Auto-generated by AlgoTutor. Do not edit by hand.
#![allow(unused_imports, unused_mut, unused_variables, dead_code, non_snake_case, non_camel_case_types)]

use std::cell::RefCell;
use std::io::{self, Read, Write};
use std::rc::Rc;

use serde::{Deserialize, Serialize};

// === Standard data structures (canonical) ===
#[derive(Debug, PartialEq, Eq, Clone)]
pub struct ListNode {
    pub val: i32,
    pub next: Option<Box<ListNode>>,
}
impl ListNode {
    #[inline]
    pub fn new(val: i32) -> Self { ListNode { val, next: None } }
}

#[derive(Debug, PartialEq, Eq, Clone)]
pub struct TreeNode {
    pub val: i32,
    pub left: Option<Rc<RefCell<TreeNode>>>,
    pub right: Option<Rc<RefCell<TreeNode>>>,
}
impl TreeNode {
    #[inline]
    pub fn new(val: i32) -> Self { TreeNode { val, left: None, right: None } }
}

// === Wire adapters ===
fn array_to_list(arr: Vec<i32>) -> Option<Box<ListNode>> {
    let mut head: Option<Box<ListNode>> = None;
    for v in arr.into_iter().rev() {
        let mut n = Box::new(ListNode::new(v));
        n.next = head;
        head = Some(n);
    }
    head
}
fn list_to_array(mut head: Option<Box<ListNode>>) -> Vec<i32> {
    let mut out = Vec::new();
    while let Some(node) = head {
        out.push(node.val);
        head = node.next;
    }
    out
}
fn array_to_tree(arr: Vec<Option<i32>>) -> Option<Rc<RefCell<TreeNode>>> {
    if arr.is_empty() || arr[0].is_none() { return None; }
    let root = Rc::new(RefCell::new(TreeNode::new(arr[0].unwrap())));
    let mut q: std::collections::VecDeque<Rc<RefCell<TreeNode>>> = std::collections::VecDeque::new();
    q.push_back(root.clone());
    let mut i = 1usize;
    while !q.is_empty() && i < arr.len() {
        let node = q.pop_front().unwrap();
        if i < arr.len() {
            if let Some(v) = arr[i] {
                let l = Rc::new(RefCell::new(TreeNode::new(v)));
                node.borrow_mut().left = Some(l.clone());
                q.push_back(l);
            }
            i += 1;
        }
        if i < arr.len() {
            if let Some(v) = arr[i] {
                let r = Rc::new(RefCell::new(TreeNode::new(v)));
                node.borrow_mut().right = Some(r.clone());
                q.push_back(r);
            }
            i += 1;
        }
    }
    Some(root)
}
fn tree_to_array(root: Option<Rc<RefCell<TreeNode>>>) -> Vec<Option<i32>> {
    let mut out: Vec<Option<i32>> = Vec::new();
    if root.is_none() { return out; }
    let mut q: std::collections::VecDeque<Option<Rc<RefCell<TreeNode>>>> = std::collections::VecDeque::new();
    q.push_back(root);
    while let Some(n) = q.pop_front() {
        match n {
            None => out.push(None),
            Some(rc) => {
                let b = rc.borrow();
                out.push(Some(b.val));
                q.push_back(b.left.clone());
                q.push_back(b.right.clone());
            }
        }
    }
    while let Some(last) = out.last() {
        if last.is_none() { out.pop(); } else { break; }
    }
    out
}
`;

// camelCase → snake_case for fields where Rust requires it. We don't actually
// enforce snake_case on user fns (we suppress the warning) so the user can
// keep the camelCase name from the prompt.
function deriveStruct(name, fields) {
  const lines = fields.map(({ key, type, rename }) => {
    if (rename && rename !== key) return `    #[serde(rename = "${rename}")]\n    pub ${key}: ${type},`;
    return `    pub ${key}: ${type},`;
  }).join("\n");
  return `#[derive(Deserialize)]\npub struct ${name} {\n${lines}\n}`;
}

// Map a paramAdapter to the wire-side Rust type (what arrives in stdin JSON).
function wireType(paramAdapter) {
  switch (paramAdapter) {
    case "arrayToLinkedList": return "Vec<i32>";
    case "arrayToBinaryTree": return "Vec<Option<i32>>";
    default: return null; // identity → use the user-facing type
  }
}

// Strip `&mut ` prefix when declaring the wire-deserialization type.
function stripMut(t) {
  return t.replace(/^&\s*mut\s+/, "").trim();
}

export function generateRustFunctionHarness(question, userCode) {
  const sig = question.signature;
  const fnName = sig.fn; // e.g., "twoSum"
  const ct = sig.codeTypes.rust;
  const judge = sig.judgeSource || "return";

  // Per-param spec.
  const params = sig.params.map((p, i) => {
    const ut = ct.params[i].type;
    const adapt = p.adapt || "identity";
    const wt = wireType(adapt) || stripMut(ut);
    return { name: p.name, userType: ut, wireType: wt, adapt };
  });

  // Build TestInput struct from wire-side types.
  const inputStruct = deriveStruct(
    "TestInput",
    params.map((p) => ({ key: p.name, type: p.wireType }))
  );

  // For each param, materialize a binding from t.input.<name> → user-callable value.
  // For mutation params (`&mut T`) we keep a mut local so we can re-serialize after.
  const isMutation = judge.startsWith("param:");
  const mutIdx = isMutation ? Number(judge.slice(6)) : -1;

  const bindLines = params.map((p, i) => {
    const isMut = i === mutIdx || p.userType.startsWith("&mut");
    const bindName = `${p.name}_in`;
    let expr;
    if (p.adapt === "arrayToLinkedList") expr = `array_to_list(input.${p.name})`;
    else if (p.adapt === "arrayToBinaryTree") expr = `array_to_tree(input.${p.name})`;
    else expr = `input.${p.name}`;
    return `        let ${isMut ? "mut " : ""}${bindName} = ${expr};`;
  }).join("\n");

  // Build call args. For mutation slot pass `&mut <name>_in`.
  const callArgs = params.map((p, i) => {
    if (i === mutIdx || p.userType.startsWith("&mut")) return `&mut ${p.name}_in`;
    return `${p.name}_in`;
  }).join(", ");

  // Build "actual" expression after the call.
  let actualExpr;
  if (isMutation) {
    const p = params[mutIdx];
    if (p.adapt === "arrayToLinkedList") actualExpr = `serde_json::to_value(list_to_array(${p.name}_in)).unwrap()`;
    else if (p.adapt === "arrayToBinaryTree") actualExpr = `serde_json::to_value(tree_to_array(${p.name}_in)).unwrap()`;
    else actualExpr = `serde_json::to_value(&${p.name}_in).unwrap()`;
  } else {
    const ra = sig.returnAdapt || "identity";
    if (ra === "linkedListToArray") actualExpr = `serde_json::to_value(list_to_array(__ret)).unwrap()`;
    else if (ra === "binaryTreeToLevelOrder") actualExpr = `serde_json::to_value(tree_to_array(__ret)).unwrap()`;
    else actualExpr = `serde_json::to_value(&__ret).unwrap()`;
  }

  // For non-mutation, the closure returns the user's value so we can bind
  // it as `__ret` in the Ok branch. For mutation, the closure returns ()
  // and we read the captured-by-mutable-borrow local after it completes.
  const closureBody = isMutation
    ? `${fnName}(${callArgs});`
    : `${fnName}(${callArgs})`;
  const okBranch = isMutation
    ? `Ok(_) => {
                let actual = ${actualExpr};
                out.push(CaseResult { index: i, ok: true, actual, duration_ms: dt, error: None });
            }`
    : `Ok(__ret) => {
                let actual = ${actualExpr};
                out.push(CaseResult { index: i, ok: true, actual, duration_ms: dt, error: None });
            }`;

  return `${PRELUDE}

// === User code ===
${userCode}
// === End user code ===

#[derive(Deserialize)]
pub struct Test { pub input: TestInput, pub output: serde_json::Value }
${inputStruct}

#[derive(Deserialize)]
pub struct Request { pub tests: Vec<Test> }

#[derive(Serialize)]
pub struct CaseResult {
    pub index: usize,
    pub ok: bool,
    pub actual: serde_json::Value,
    #[serde(rename = "durationMs")]
    pub duration_ms: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[derive(Serialize)]
pub struct Response { pub results: Vec<CaseResult> }

fn panic_message(e: Box<dyn std::any::Any + Send>) -> String {
    if let Some(s) = e.downcast_ref::<&str>() { return (*s).to_string(); }
    if let Some(s) = e.downcast_ref::<String>() { return s.clone(); }
    "panic".to_string()
}

fn main() {
    let mut buf = String::new();
    io::stdin().read_to_string(&mut buf).unwrap();
    let req: Request = match serde_json::from_str(&buf) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("__HARNESS_PARSE_ERROR__: {}", e);
            std::process::exit(2);
        }
    };
    let mut out: Vec<CaseResult> = Vec::with_capacity(req.tests.len());
    for (i, t) in req.tests.into_iter().enumerate() {
        let Test { input, output: _ } = t;
${bindLines}
        let started = std::time::Instant::now();
        let res = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            ${closureBody}
        }));
        let dt = started.elapsed().as_millis() as u64;
        match res {
            ${okBranch}
            Err(e) => {
                out.push(CaseResult { index: i, ok: false, actual: serde_json::Value::Null, duration_ms: dt, error: Some(panic_message(e)) });
            }
        }
    }
    let resp = Response { results: out };
    let s = serde_json::to_string(&resp).unwrap();
    let stdout = io::stdout();
    stdout.lock().write_all(s.as_bytes()).unwrap();
}
`;
}

// === Design harness ===
// User code defines `pub struct ClassName { ... }` + `impl ClassName { fn new(...) -> Self; ...methods }`.
// Wire input: either { ops: [[name, ...args], ...] } (ops-tuples)
// or { operations: [name, ...], args: [[...], ...] } (ops-args).
// Output: per test, an array of method return values (Null for void).
export function generateRustDesignHarness(question, userCode) {
  const sig = question.signature;
  const design = sig.design;
  const className = design.className;
  const ctorParams = (design.ctor && design.ctor.params) || [];
  const methods = design.methods || [];

  const ctorArgBindings = ctorParams.map((p, i) => {
    const t = p.type.rust;
    return `            let __c${i}: ${t} = serde_json::from_value(args[${i}].clone()).expect("ctor arg ${i} (${p.name}) parse");`;
  }).join("\n");
  const ctorArgList = ctorParams.map((_, i) => `__c${i}`).join(", ");

  const methodArms = methods.map((m) => {
    const argBindings = m.params.map((p, i) => {
      const t = p.type.rust;
      return `                let __a${i}: ${t} = serde_json::from_value(args[${i}].clone()).expect("${m.name} arg ${i} (${p.name}) parse");`;
    }).join("\n");
    const argList = m.params.map((_, i) => `__a${i}`).join(", ");
    const ret = (m.returns && m.returns.rust) || "()";
    const isVoid = ret === "()" || ret === "" || ret == null;
    const callBlock = isVoid
      ? `                inst.${m.name}(${argList});\n                out.push(serde_json::Value::Null);`
      : `                let __r = inst.${m.name}(${argList});\n                out.push(serde_json::to_value(__r).unwrap());`;
    return `            "${m.name}" => {
${argBindings}
${callBlock}
            }`;
  }).join("\n");

  return `${PRELUDE}

// === User code ===
${userCode}
// === End user code ===

#[derive(Deserialize, Default)]
pub struct DesignInput {
    #[serde(default)]
    pub ops: Vec<Vec<serde_json::Value>>,
    #[serde(default)]
    pub operations: Vec<String>,
    #[serde(default)]
    pub args: Vec<Vec<serde_json::Value>>,
}

#[derive(Deserialize)]
pub struct Test { pub input: DesignInput, pub output: serde_json::Value }
#[derive(Deserialize)]
pub struct Request { pub tests: Vec<Test> }

#[derive(Serialize)]
pub struct CaseResult {
    pub index: usize,
    pub ok: bool,
    pub actual: serde_json::Value,
    #[serde(rename = "durationMs")]
    pub duration_ms: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[derive(Serialize)]
pub struct Response { pub results: Vec<CaseResult> }

fn panic_message(e: Box<dyn std::any::Any + Send>) -> String {
    if let Some(s) = e.downcast_ref::<&str>() { return (*s).to_string(); }
    if let Some(s) = e.downcast_ref::<String>() { return s.clone(); }
    "panic".to_string()
}

fn run_one(input: DesignInput) -> Vec<serde_json::Value> {
    let (methods, all_args): (Vec<String>, Vec<Vec<serde_json::Value>>) = if !input.ops.is_empty() {
        let mut ms = Vec::with_capacity(input.ops.len());
        let mut args_v = Vec::with_capacity(input.ops.len());
        for op in input.ops.into_iter() {
            let mut it = op.into_iter();
            let head = it.next().expect("empty op tuple");
            let name = head.as_str().expect("op[0] not a string").to_string();
            ms.push(name);
            args_v.push(it.collect());
        }
        (ms, args_v)
    } else {
        (input.operations, input.args)
    };

    let mut out: Vec<serde_json::Value> = Vec::with_capacity(methods.len());
    let mut instance: Option<${className}> = None;
    for (i, name) in methods.iter().enumerate() {
        let args = all_args.get(i).cloned().unwrap_or_default();
        if name == "${className}" {
${ctorArgBindings}
            instance = Some(${className}::new(${ctorArgList}));
            out.push(serde_json::Value::Null);
            continue;
        }
        if instance.is_none() {
            // Constructor not in stream; only legal when ctor has no params.
            ${ctorParams.length === 0
              ? `instance = Some(${className}::new());`
              : `panic!("first op should be the constructor (${className}) for this problem");`}
        }
        let inst = instance.as_mut().unwrap();
        match name.as_str() {
${methodArms}
            other => panic!("unknown method: {}", other),
        }
    }
    out
}

fn main() {
    let mut buf = String::new();
    io::stdin().read_to_string(&mut buf).unwrap();
    let req: Request = match serde_json::from_str(&buf) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("__HARNESS_PARSE_ERROR__: {}", e);
            std::process::exit(2);
        }
    };
    let mut out: Vec<CaseResult> = Vec::with_capacity(req.tests.len());
    for (i, t) in req.tests.into_iter().enumerate() {
        let Test { input, output: _ } = t;
        let started = std::time::Instant::now();
        let res = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| run_one(input)));
        let dt = started.elapsed().as_millis() as u64;
        match res {
            Ok(actual) => {
                out.push(CaseResult { index: i, ok: true, actual: serde_json::to_value(actual).unwrap(), duration_ms: dt, error: None });
            }
            Err(e) => {
                out.push(CaseResult { index: i, ok: false, actual: serde_json::Value::Null, duration_ms: dt, error: Some(panic_message(e)) });
            }
        }
    }
    let resp = Response { results: out };
    let s = serde_json::to_string(&resp).unwrap();
    let stdout = io::stdout();
    stdout.lock().write_all(s.as_bytes()).unwrap();
}
`;
}

// Top-level dispatcher.
export function generateRustHarness(question, userCode) {
  const kind = question.signature.kind || "function";
  if (kind === "function") return generateRustFunctionHarness(question, userCode);
  if (kind === "design") return generateRustDesignHarness(question, userCode);
  throw new Error(`unsupported kind for Rust: ${kind}`);
}
