// Auto-generated by AlgoTutor. Do not edit by hand.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"time"
)

var _ = fmt.Sprintf
var _ = time.Now

// === Standard data structures (canonical) ===
type ListNode struct {
	Val  int
	Next *ListNode
}

type TreeNode struct {
	Val   int
	Left  *TreeNode
	Right *TreeNode
}

// === Wire adapters ===
func arrayToList(arr []int) *ListNode {
	var head *ListNode
	for i := len(arr) - 1; i >= 0; i-- {
		head = &ListNode{Val: arr[i], Next: head}
	}
	return head
}

func listToArray(head *ListNode) []int {
	out := []int{}
	for head != nil {
		out = append(out, head.Val)
		head = head.Next
	}
	return out
}

func arrayToTree(arr []*int) *TreeNode {
	if len(arr) == 0 || arr[0] == nil {
		return nil
	}
	root := &TreeNode{Val: *arr[0]}
	q := []*TreeNode{root}
	i := 1
	for len(q) > 0 && i < len(arr) {
		node := q[0]
		q = q[1:]
		if i < len(arr) {
			if arr[i] != nil {
				node.Left = &TreeNode{Val: *arr[i]}
				q = append(q, node.Left)
			}
			i++
		}
		if i < len(arr) {
			if arr[i] != nil {
				node.Right = &TreeNode{Val: *arr[i]}
				q = append(q, node.Right)
			}
			i++
		}
	}
	return root
}

func treeToArray(root *TreeNode) []*int {
	out := []*int{}
	if root == nil {
		return out
	}
	type qe struct{ n *TreeNode }
	q := []qe{{root}}
	for len(q) > 0 {
		front := q[0]
		q = q[1:]
		if front.n == nil {
			out = append(out, nil)
			continue
		}
		v := front.n.Val
		out = append(out, &v)
		q = append(q, qe{front.n.Left}, qe{front.n.Right})
	}
	for len(out) > 0 && out[len(out)-1] == nil {
		out = out[:len(out)-1]
	}
	return out
}

// === Wire-shape structs for graph/random-list problems ===
type RandomList struct {
	Vals    []int  `json:"vals"`
	Randoms []*int `json:"randoms"`
}
type GraphRepr struct {
	Nodes []int   `json:"nodes"`
	Adj   [][]int `json:"adj"`
}


// === User code ===
type LRUCache struct {
    cap int
    order []int
    m map[int]int
}
func Constructor(capacity int) LRUCache {
    return LRUCache{cap: capacity, order: []int{}, m: map[int]int{}}
}
func (c *LRUCache) get(key int) int {
    v, ok := c.m[key]
    if !ok { return -1 }
    for i, k := range c.order { if k == key { c.order = append(c.order[:i], c.order[i+1:]...); break } }
    c.order = append(c.order, key)
    return v
}
func (c *LRUCache) put(key int, value int) {
    if _, ok := c.m[key]; ok {
        for i, k := range c.order { if k == key { c.order = append(c.order[:i], c.order[i+1:]...); break } }
    } else if len(c.m) >= c.cap {
        ev := c.order[0]; c.order = c.order[1:]; delete(c.m, ev)
    }
    c.m[key] = value
    c.order = append(c.order, key)
}
// === End user code ===

type DesignInput struct {
	Ops        [][]json.RawMessage `json:"ops,omitempty"`
	Operations []string            `json:"operations,omitempty"`
	Args       [][]json.RawMessage `json:"args,omitempty"`
}

type Test struct {
	Input  DesignInput     `json:"input"`
	Output json.RawMessage `json:"output"`
}

type Request struct {
	Tests []Test `json:"tests"`
}

type CaseResult struct {
	Index      int             `json:"index"`
	OK         bool            `json:"ok"`
	Actual     json.RawMessage `json:"actual,omitempty"`
	DurationMs int64           `json:"durationMs"`
	Error      string          `json:"error,omitempty"`
}

type Response struct {
	Results []CaseResult `json:"results"`
}

// Helper to construct a default-initialized instance for "ctor not in stream"
// (only used when ctor has zero params).


func runOneCase(i int, t Test) (cr CaseResult) {
	cr.Index = i
	started := time.Now()
	defer func() {
		cr.DurationMs = time.Since(started).Milliseconds()
		if r := recover(); r != nil {
			cr.OK = false
			cr.Error = fmt.Sprintf("%v", r)
		}
	}()
	input := t.Input
	var methods []string
	var allArgs [][]json.RawMessage
	if len(input.Ops) > 0 {
		methods = make([]string, 0, len(input.Ops))
		allArgs = make([][]json.RawMessage, 0, len(input.Ops))
		for _, op := range input.Ops {
			if len(op) == 0 {
				panic("empty op tuple")
			}
			var name string
			if err := json.Unmarshal(op[0], &name); err != nil {
				panic(fmt.Sprintf("op[0] not a string: %v", err))
			}
			methods = append(methods, name)
			allArgs = append(allArgs, op[1:])
		}
	} else {
		methods = input.Operations
		allArgs = input.Args
	}

	out := make([]json.RawMessage, 0, len(methods))
	var inst *LRUCache
	for idx, name := range methods {
		var args []json.RawMessage
		if idx < len(allArgs) {
			args = allArgs[idx]
		}
		if name == "LRUCache" {
			var __c0 int
			if err := json.Unmarshal(args[0], &__c0); err != nil { panic(fmt.Sprintf("ctor arg 0 (capacity) parse: %v", err)) }
			v := Constructor(__c0)
			inst = &v
			out = append(out, json.RawMessage("null"))
			continue
		}
		if inst == nil {
			panic("first op should be the constructor (LRUCache) for this problem")
		}
		switch name {
		case "get":
				var __a0 int
				if err := json.Unmarshal(args[0], &__a0); err != nil { panic(fmt.Sprintf("get arg 0 (key) parse: %v", err)) }
				__r := inst.get(__a0)
				bs, _ := json.Marshal(__r)
				out = append(out, json.RawMessage(bs))
		case "put":
				var __a0 int
				if err := json.Unmarshal(args[0], &__a0); err != nil { panic(fmt.Sprintf("put arg 0 (key) parse: %v", err)) }
				var __a1 int
				if err := json.Unmarshal(args[1], &__a1); err != nil { panic(fmt.Sprintf("put arg 1 (value) parse: %v", err)) }
				inst.put(__a0, __a1)
				out = append(out, json.RawMessage("null"))
		default:
			panic("unknown method: " + name)
		}
	}
	bs, err := json.Marshal(out)
	if err != nil {
		cr.OK = false
		cr.Error = "marshal: " + err.Error()
		return
	}
	cr.OK = true
	cr.Actual = bs
	return
}

func main() {
	buf, err := io.ReadAll(os.Stdin)
	if err != nil {
		fmt.Fprintf(os.Stderr, "__HARNESS_READ_ERROR__: %v\n", err)
		os.Exit(2)
	}
	var req Request
	if err := json.Unmarshal(buf, &req); err != nil {
		fmt.Fprintf(os.Stderr, "__HARNESS_PARSE_ERROR__: %v\n", err)
		os.Exit(2)
	}
	out := make([]CaseResult, 0, len(req.Tests))
	for i, t := range req.Tests {
		out = append(out, runOneCase(i, t))
	}
	resp := Response{Results: out}
	bs, _ := json.Marshal(resp)
	os.Stdout.Write(bs)
}
