// Auto-generated by AlgoTutor. Do not edit by hand.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"time"
)

var _ = fmt.Sprintf
var _ = time.Now

// === Standard data structures (canonical) ===
type ListNode struct {
	Val  int
	Next *ListNode
}

type TreeNode struct {
	Val   int
	Left  *TreeNode
	Right *TreeNode
}

// === Wire adapters ===
func arrayToList(arr []int) *ListNode {
	var head *ListNode
	for i := len(arr) - 1; i >= 0; i-- {
		head = &ListNode{Val: arr[i], Next: head}
	}
	return head
}

func listToArray(head *ListNode) []int {
	out := []int{}
	for head != nil {
		out = append(out, head.Val)
		head = head.Next
	}
	return out
}

func arrayToTree(arr []*int) *TreeNode {
	if len(arr) == 0 || arr[0] == nil {
		return nil
	}
	root := &TreeNode{Val: *arr[0]}
	q := []*TreeNode{root}
	i := 1
	for len(q) > 0 && i < len(arr) {
		node := q[0]
		q = q[1:]
		if i < len(arr) {
			if arr[i] != nil {
				node.Left = &TreeNode{Val: *arr[i]}
				q = append(q, node.Left)
			}
			i++
		}
		if i < len(arr) {
			if arr[i] != nil {
				node.Right = &TreeNode{Val: *arr[i]}
				q = append(q, node.Right)
			}
			i++
		}
	}
	return root
}

func treeToArray(root *TreeNode) []*int {
	out := []*int{}
	if root == nil {
		return out
	}
	type qe struct{ n *TreeNode }
	q := []qe{{root}}
	for len(q) > 0 {
		front := q[0]
		q = q[1:]
		if front.n == nil {
			out = append(out, nil)
			continue
		}
		v := front.n.Val
		out = append(out, &v)
		q = append(q, qe{front.n.Left}, qe{front.n.Right})
	}
	for len(out) > 0 && out[len(out)-1] == nil {
		out = out[:len(out)-1]
	}
	return out
}


// === User code ===

func twoSum(nums []int, target int) []int {
    m := map[int]int{}
    for i, n := range nums {
        if j, ok := m[target-n]; ok { return []int{j, i} }
        m[n] = i
    }
    return nil
}
// === End user code ===

type TestInput struct {
	Nums []int `json:"nums"`
	Target int `json:"target"`
}

type Test struct {
	Input  TestInput       `json:"input"`
	Output json.RawMessage `json:"output"`
}

type Request struct {
	Tests []Test `json:"tests"`
}

type CaseResult struct {
	Index      int             `json:"index"`
	OK         bool            `json:"ok"`
	Actual     json.RawMessage `json:"actual,omitempty"`
	DurationMs int64           `json:"durationMs"`
	Error      string          `json:"error,omitempty"`
}

type Response struct {
	Results []CaseResult `json:"results"`
}

func runOneCase(i int, t Test) (cr CaseResult) {
	cr.Index = i
	started := time.Now()
	defer func() {
		cr.DurationMs = time.Since(started).Milliseconds()
		if r := recover(); r != nil {
			cr.OK = false
			cr.Error = fmt.Sprintf("%v", r)
		}
	}()
	input := t.Input
	_ = input
	var actualVal interface{}
	func() {
		nums := input.Nums
		target := input.Target
			__ret := twoSum(nums, target)
			actualVal = __ret
	}()
	bs, err := json.Marshal(actualVal)
	if err != nil {
		cr.OK = false
		cr.Error = "marshal: " + err.Error()
		return
	}
	cr.OK = true
	cr.Actual = bs
	return
}

func main() {
	buf, err := io.ReadAll(os.Stdin)
	if err != nil {
		fmt.Fprintf(os.Stderr, "__HARNESS_READ_ERROR__: %v\n", err)
		os.Exit(2)
	}
	var req Request
	if err := json.Unmarshal(buf, &req); err != nil {
		fmt.Fprintf(os.Stderr, "__HARNESS_PARSE_ERROR__: %v\n", err)
		os.Exit(2)
	}
	out := make([]CaseResult, 0, len(req.Tests))
	for i, t := range req.Tests {
		out = append(out, runOneCase(i, t))
	}
	resp := Response{Results: out}
	bs, _ := json.Marshal(resp)
	os.Stdout.Write(bs)
}
