// Auto-generated by AlgoTutor. Do not edit by hand.
#![allow(unused_imports, unused_mut, unused_variables, dead_code, non_snake_case, non_camel_case_types)]

use std::cell::RefCell;
use std::io::{self, Read, Write};
use std::rc::Rc;

use serde::{Deserialize, Serialize};

// === Standard data structures (canonical) ===
#[derive(Debug, PartialEq, Eq, Clone)]
pub struct ListNode {
    pub val: i32,
    pub next: Option<Box<ListNode>>,
}
impl ListNode {
    #[inline]
    pub fn new(val: i32) -> Self { ListNode { val, next: None } }
}

#[derive(Debug, PartialEq, Eq, Clone)]
pub struct TreeNode {
    pub val: i32,
    pub left: Option<Rc<RefCell<TreeNode>>>,
    pub right: Option<Rc<RefCell<TreeNode>>>,
}
impl TreeNode {
    #[inline]
    pub fn new(val: i32) -> Self { TreeNode { val, left: None, right: None } }
}

// === Wire adapters ===
fn array_to_list(arr: Vec<i32>) -> Option<Box<ListNode>> {
    let mut head: Option<Box<ListNode>> = None;
    for v in arr.into_iter().rev() {
        let mut n = Box::new(ListNode::new(v));
        n.next = head;
        head = Some(n);
    }
    head
}
fn list_to_array(mut head: Option<Box<ListNode>>) -> Vec<i32> {
    let mut out = Vec::new();
    while let Some(node) = head {
        out.push(node.val);
        head = node.next;
    }
    out
}
fn array_to_tree(arr: Vec<Option<i32>>) -> Option<Rc<RefCell<TreeNode>>> {
    if arr.is_empty() || arr[0].is_none() { return None; }
    let root = Rc::new(RefCell::new(TreeNode::new(arr[0].unwrap())));
    let mut q: std::collections::VecDeque<Rc<RefCell<TreeNode>>> = std::collections::VecDeque::new();
    q.push_back(root.clone());
    let mut i = 1usize;
    while !q.is_empty() && i < arr.len() {
        let node = q.pop_front().unwrap();
        if i < arr.len() {
            if let Some(v) = arr[i] {
                let l = Rc::new(RefCell::new(TreeNode::new(v)));
                node.borrow_mut().left = Some(l.clone());
                q.push_back(l);
            }
            i += 1;
        }
        if i < arr.len() {
            if let Some(v) = arr[i] {
                let r = Rc::new(RefCell::new(TreeNode::new(v)));
                node.borrow_mut().right = Some(r.clone());
                q.push_back(r);
            }
            i += 1;
        }
    }
    Some(root)
}
fn tree_to_array(root: Option<Rc<RefCell<TreeNode>>>) -> Vec<Option<i32>> {
    let mut out: Vec<Option<i32>> = Vec::new();
    if root.is_none() { return out; }
    let mut q: std::collections::VecDeque<Option<Rc<RefCell<TreeNode>>>> = std::collections::VecDeque::new();
    q.push_back(root);
    while let Some(n) = q.pop_front() {
        match n {
            None => out.push(None),
            Some(rc) => {
                let b = rc.borrow();
                out.push(Some(b.val));
                q.push_back(b.left.clone());
                q.push_back(b.right.clone());
            }
        }
    }
    while let Some(last) = out.last() {
        if last.is_none() { out.pop(); } else { break; }
    }
    out
}

// === Wire-shape structs for graph/random-list problems ===
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RandomList {
    pub vals: Vec<i32>,
    pub randoms: Vec<Option<usize>>,
}
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GraphRepr {
    pub nodes: Vec<i32>,
    pub adj: Vec<Vec<usize>>,
}


// === User code ===

use std::collections::HashMap;

pub struct LRUCache {
    cap: usize,
    order: Vec<i32>,
    map: HashMap<i32, i32>,
}

impl LRUCache {
    pub fn new(capacity: i32) -> Self {
        LRUCache { cap: capacity as usize, order: Vec::new(), map: HashMap::new() }
    }
    pub fn get(&mut self, key: i32) -> i32 {
        if let Some(&v) = self.map.get(&key) {
            self.order.retain(|&k| k != key);
            self.order.push(key);
            v
        } else { -1 }
    }
    pub fn put(&mut self, key: i32, value: i32) {
        if self.map.contains_key(&key) {
            self.order.retain(|&k| k != key);
        } else if self.map.len() >= self.cap {
            let evict = self.order.remove(0);
            self.map.remove(&evict);
        }
        self.order.push(key);
        self.map.insert(key, value);
    }
}
// === End user code ===

#[derive(Deserialize, Default)]
pub struct DesignInput {
    #[serde(default)]
    pub ops: Vec<Vec<serde_json::Value>>,
    #[serde(default)]
    pub operations: Vec<String>,
    #[serde(default)]
    pub args: Vec<Vec<serde_json::Value>>,
}

#[derive(Deserialize)]
pub struct Test { pub input: DesignInput, pub output: serde_json::Value }
#[derive(Deserialize)]
pub struct Request { pub tests: Vec<Test> }

#[derive(Serialize)]
pub struct CaseResult {
    pub index: usize,
    pub ok: bool,
    pub actual: serde_json::Value,
    #[serde(rename = "durationMs")]
    pub duration_ms: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[derive(Serialize)]
pub struct Response { pub results: Vec<CaseResult> }

fn panic_message(e: Box<dyn std::any::Any + Send>) -> String {
    if let Some(s) = e.downcast_ref::<&str>() { return (*s).to_string(); }
    if let Some(s) = e.downcast_ref::<String>() { return s.clone(); }
    "panic".to_string()
}

fn run_one(input: DesignInput) -> Vec<serde_json::Value> {
    let (methods, all_args): (Vec<String>, Vec<Vec<serde_json::Value>>) = if !input.ops.is_empty() {
        let mut ms = Vec::with_capacity(input.ops.len());
        let mut args_v = Vec::with_capacity(input.ops.len());
        for op in input.ops.into_iter() {
            let mut it = op.into_iter();
            let head = it.next().expect("empty op tuple");
            let name = head.as_str().expect("op[0] not a string").to_string();
            ms.push(name);
            args_v.push(it.collect());
        }
        (ms, args_v)
    } else {
        (input.operations, input.args)
    };

    let mut out: Vec<serde_json::Value> = Vec::with_capacity(methods.len());
    let mut instance: Option<LRUCache> = None;
    for (i, name) in methods.iter().enumerate() {
        let args = all_args.get(i).cloned().unwrap_or_default();
        if name == "LRUCache" {
            let __c0: i32 = serde_json::from_value(args[0].clone()).expect("ctor arg 0 (capacity) parse");
            instance = Some(LRUCache::new(__c0));
            out.push(serde_json::Value::Null);
            continue;
        }
        if instance.is_none() {
            // Constructor not in stream; only legal when ctor has no params.
            panic!("first op should be the constructor (LRUCache) for this problem");
        }
        let inst = instance.as_mut().unwrap();
        match name.as_str() {
            "get" => {
                let __a0: i32 = serde_json::from_value(args[0].clone()).expect("get arg 0 (key) parse");
                let __r = inst.get(__a0);
                out.push(serde_json::to_value(__r).unwrap());
            }
            "put" => {
                let __a0: i32 = serde_json::from_value(args[0].clone()).expect("put arg 0 (key) parse");
                let __a1: i32 = serde_json::from_value(args[1].clone()).expect("put arg 1 (value) parse");
                inst.put(__a0, __a1);
                out.push(serde_json::Value::Null);
            }
            other => panic!("unknown method: {}", other),
        }
    }
    out
}

fn main() {
    let mut buf = String::new();
    io::stdin().read_to_string(&mut buf).unwrap();
    let req: Request = match serde_json::from_str(&buf) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("__HARNESS_PARSE_ERROR__: {}", e);
            std::process::exit(2);
        }
    };
    let mut out: Vec<CaseResult> = Vec::with_capacity(req.tests.len());
    for (i, t) in req.tests.into_iter().enumerate() {
        let Test { input, output: _ } = t;
        let started = std::time::Instant::now();
        let res = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| run_one(input)));
        let dt = started.elapsed().as_millis() as u64;
        match res {
            Ok(actual) => {
                out.push(CaseResult { index: i, ok: true, actual: serde_json::to_value(actual).unwrap(), duration_ms: dt, error: None });
            }
            Err(e) => {
                out.push(CaseResult { index: i, ok: false, actual: serde_json::Value::Null, duration_ms: dt, error: Some(panic_message(e)) });
            }
        }
    }
    let resp = Response { results: out };
    let s = serde_json::to_string(&resp).unwrap();
    let stdout = io::stdout();
    stdout.lock().write_all(s.as_bytes()).unwrap();
}
